[build]
  publish = "public"
  command = ""

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

# Per-function settings (valid syntax)
[functions."openai-image"]
  timeout = 26

[[redirects]]
  from = "/api/openai-image"
  to = "/.netlify/functions/openai-image"
  status = 200
