[build]
  publish = "public"
  command = ""

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"   # <-- makes the folder explicit

[functions."img-gen"]
  timeout = 26

# Optional shortcut for key check
[[redirects]]
  from = "/api/key-check"
  to = "/.netlify/functions/key-check"
  status = 200

# Optional: keep old route for legacy frontends
[[redirects]]
  from = "/api/openai-image"
  to = "/.netlify/functions/img-gen"
  status = 200
