[build]
  publish = "public"
  command = ""

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[functions."openai-image"]
  timeout = 26

# Optional redirect (frontend already calls the direct path first)
[[redirects]]
  from = "/api/openai-image"
  to = "/.netlify/functions/openai-image"
  status = 200
